[project]
name = "RRIviz"
version = "0.1.0"
description = "A Python-based application for simulating and visualizing complex visibilities in radio astronomy."
authors = ["Kartik Mandar <mandarkartik@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
start = "python src/main.py"
lint = "ruff check ."
fix = "ruff check --fix ."
format = "black ."
check-format = "black --check . && ruff format --check ."

[dependencies]
python = "=3.11"
numpy = "*"
matplotlib = "*"
astropy = "*"
bokeh = "*"
plotly = "*"
astroquery = "*"
pyyaml = "*"
pyuvdata = "*"
tqdm = "*"
h5py = "*"
healpy = "*"
pympler = "*"
black="*"
ruff="*"

[pypi-dependencies]
pygdsm = "*"
