"""RRIVis Streamlit App for Hugging Face Spaces.

Interactive radio interferometer visibility simulator using the RIME
(Radio Interferometer Measurement Equation).
"""

import tempfile
import time
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
import streamlit as st

# --- Page Config ---
st.set_page_config(
    page_title="RRIVis - Visibility Simulator",
    page_icon="📡",
    layout="wide",
    initial_sidebar_state="expanded",
)

# --- Constants ---
ANTENNA_LAYOUTS_DIR = Path(__file__).parent / "antenna_layouts"

PRESET_LOCATIONS = {
    "HERA (South Africa)": {"lat": -30.72153, "lon": 21.42830, "height": 1073.0},
    "MeerKAT (South Africa)": {"lat": -30.71106, "lon": 21.44389, "height": 1086.6},
    "VLA (New Mexico, USA)": {"lat": 34.07875, "lon": -107.61828, "height": 2124.0},
    "LOFAR (Netherlands)": {"lat": 52.90533, "lon": 6.86764, "height": 49.3},
    "MWA (Australia)": {"lat": -26.70332, "lon": 116.67085, "height": 377.8},
    "Custom": {"lat": 0.0, "lon": 0.0, "height": 0.0},
}

ANTENNA_LAYOUT_FILES = {
    "HERA-like Grid (10 antennas)": {
        "file": "example_rrivis_format.txt",
        "format": "rrivis",
    },
    "HERA-5 (5 antennas)": {
        "file": "hera_5.txt",
        "format": "rrivis",
    },
    "CASA Format Example (10 antennas)": {
        "file": "example_casa_format.cfg",
        "format": "casa",
    },
}


def create_custom_antenna_layout(
    n_antennas: int, layout_type: str, spacing: float, diameter: float
) -> str:
    """Generate a custom antenna layout file content."""
    lines = [
        "# Custom Antenna Layout",
        "# Generated by RRIVis Streamlit App",
        "Name    Number  BeamID  E            N            U           Diameter",
    ]

    if layout_type == "Linear (E-W)":
        for i in range(n_antennas):
            e = i * spacing
            lines.append(
                f"ANT{i:03d}   {i}       0       {e:.2f}         0.00         0.0         {diameter}"
            )
    elif layout_type == "Linear (N-S)":
        for i in range(n_antennas):
            n = i * spacing
            lines.append(
                f"ANT{i:03d}   {i}       0       0.00         {n:.2f}         0.0         {diameter}"
            )
    elif layout_type == "Y-shaped":
        arm_length = n_antennas // 3
        remainder = n_antennas - 3 * arm_length
        idx = 0
        # East arm
        for i in range(arm_length + (1 if remainder > 0 else 0)):
            e = i * spacing
            lines.append(
                f"ANT{idx:03d}   {idx}       0       {e:.2f}         0.00         0.0         {diameter}"
            )
            idx += 1
        # NW arm (120 degrees)
        for i in range(1, arm_length + (1 if remainder > 1 else 0) + 1):
            e = -i * spacing * np.cos(np.radians(60))
            n = i * spacing * np.sin(np.radians(60))
            lines.append(
                f"ANT{idx:03d}   {idx}       0       {e:.2f}         {n:.2f}         0.0         {diameter}"
            )
            idx += 1
        # SW arm (240 degrees)
        for i in range(1, arm_length + 1):
            e = -i * spacing * np.cos(np.radians(60))
            n = -i * spacing * np.sin(np.radians(60))
            lines.append(
                f"ANT{idx:03d}   {idx}       0       {e:.2f}         {n:.2f}         0.0         {diameter}"
            )
            idx += 1
    elif layout_type == "Circle":
        radius = spacing * n_antennas / (2 * np.pi)
        for i in range(n_antennas):
            angle = 2 * np.pi * i / n_antennas
            e = radius * np.cos(angle)
            n = radius * np.sin(angle)
            lines.append(
                f"ANT{i:03d}   {i}       0       {e:.2f}         {n:.2f}         0.0         {diameter}"
            )
    elif layout_type == "Hex Grid":
        side = int(np.ceil(np.sqrt(n_antennas)))
        idx = 0
        for row in range(side):
            for col in range(side):
                if idx >= n_antennas:
                    break
                e = col * spacing + (row % 2) * spacing / 2
                n = row * spacing * np.sqrt(3) / 2
                lines.append(
                    f"ANT{idx:03d}   {idx}       0       {e:.2f}         {n:.2f}         0.0         {diameter}"
                )
                idx += 1
    else:
        # Random
        rng = np.random.default_rng(42)
        max_extent = spacing * np.sqrt(n_antennas)
        for i in range(n_antennas):
            e = rng.uniform(-max_extent / 2, max_extent / 2)
            n = rng.uniform(-max_extent / 2, max_extent / 2)
            lines.append(
                f"ANT{i:03d}   {i}       0       {e:.2f}         {n:.2f}         0.0         {diameter}"
            )

    return "\n".join(lines) + "\n"


def plot_antenna_layout(antennas: dict) -> go.Figure:
    """Plot antenna positions using Plotly."""
    east = [ant["E"] for ant in antennas.values()]
    north = [ant["N"] for ant in antennas.values()]
    names = [ant["Name"] for ant in antennas.values()]

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=east,
            y=north,
            mode="markers+text",
            text=names,
            textposition="top center",
            textfont={"size": 9},
            marker={"size": 10, "color": "#1f77b4", "symbol": "circle"},
            name="Antennas",
        )
    )
    fig.update_layout(
        title="Antenna Layout (ENU Coordinates)",
        xaxis_title="East (m)",
        yaxis_title="North (m)",
        xaxis={"scaleanchor": "y", "scaleratio": 1},
        height=500,
        template="plotly_white",
    )
    return fig


def plot_uv_coverage(baselines: dict, wavelengths) -> go.Figure:
    """Plot UV coverage."""
    u_all, v_all = [], []
    for _bl_key, bl_data in baselines.items():
        bl_vec = np.array([bl_data["E"], bl_data["N"], bl_data.get("U", 0.0)])
        for wl in wavelengths:
            wl_val = wl.value if hasattr(wl, "value") else float(wl)
            u = bl_vec[0] / wl_val
            v = bl_vec[1] / wl_val
            u_all.extend([u, -u])
            v_all.extend([v, -v])

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=u_all,
            y=v_all,
            mode="markers",
            marker={"size": 2, "color": "#1f77b4", "opacity": 0.5},
            name="UV points",
        )
    )
    fig.update_layout(
        title="UV Coverage",
        xaxis_title="u (wavelengths)",
        yaxis_title="v (wavelengths)",
        xaxis={"scaleanchor": "y", "scaleratio": 1},
        height=500,
        template="plotly_white",
    )
    return fig


def plot_visibility_spectrum(results: dict) -> go.Figure:
    """Plot visibility amplitude vs frequency for all baselines."""
    visibilities = results["visibilities"]
    freqs_mhz = results["frequencies"] / 1e6

    fig = go.Figure()
    for bl_key, bl_vis in visibilities.items():
        # Get Stokes I visibility
        vis_I = bl_vis.get("I", bl_vis.get("XX", None))
        if vis_I is None:
            continue

        # Handle shape: (n_times, n_freqs) or (n_freqs,)
        if vis_I.ndim == 2:
            amp = np.abs(vis_I[0, :])  # First time step
        else:
            amp = np.abs(vis_I)

        fig.add_trace(
            go.Scatter(
                x=freqs_mhz,
                y=amp,
                mode="lines",
                name=f"Baseline {bl_key}",
                opacity=0.7,
                line={"width": 1.5},
            )
        )

    fig.update_layout(
        title="Visibility Amplitude vs Frequency (Stokes I, t=0)",
        xaxis_title="Frequency (MHz)",
        yaxis_title="Visibility Amplitude (Jy)",
        height=500,
        template="plotly_white",
        showlegend=True,
        legend={"font": {"size": 8}},
    )
    return fig


def plot_visibility_phase(results: dict) -> go.Figure:
    """Plot visibility phase vs frequency for all baselines."""
    visibilities = results["visibilities"]
    freqs_mhz = results["frequencies"] / 1e6

    fig = go.Figure()
    for bl_key, bl_vis in visibilities.items():
        vis_I = bl_vis.get("I", bl_vis.get("XX", None))
        if vis_I is None:
            continue

        if vis_I.ndim == 2:
            phase = np.angle(vis_I[0, :], deg=True)
        else:
            phase = np.angle(vis_I, deg=True)

        fig.add_trace(
            go.Scatter(
                x=freqs_mhz,
                y=phase,
                mode="lines",
                name=f"Baseline {bl_key}",
                opacity=0.7,
                line={"width": 1.5},
            )
        )

    fig.update_layout(
        title="Visibility Phase vs Frequency (Stokes I, t=0)",
        xaxis_title="Frequency (MHz)",
        yaxis_title="Phase (degrees)",
        height=500,
        template="plotly_white",
        showlegend=True,
        legend={"font": {"size": 8}},
    )
    return fig


def plot_visibility_matrix(results: dict) -> go.Figure:
    """Plot visibility amplitude as a baseline-frequency heatmap."""
    visibilities = results["visibilities"]
    freqs_mhz = results["frequencies"] / 1e6
    bl_keys = list(visibilities.keys())

    n_bl = len(bl_keys)
    n_freq = len(freqs_mhz)
    matrix = np.zeros((n_bl, n_freq))

    for i, bl_key in enumerate(bl_keys):
        vis_I = visibilities[bl_key].get("I", visibilities[bl_key].get("XX", None))
        if vis_I is None:
            continue
        if vis_I.ndim == 2:
            matrix[i, :] = np.abs(vis_I[0, :])
        else:
            matrix[i, :] = np.abs(vis_I)

    bl_labels = [str(k) for k in bl_keys]

    fig = go.Figure(
        data=go.Heatmap(
            z=matrix,
            x=freqs_mhz,
            y=bl_labels,
            colorscale="Viridis",
            colorbar={"title": "Amplitude (Jy)"},
        )
    )
    fig.update_layout(
        title="Visibility Amplitude Heatmap (Stokes I, t=0)",
        xaxis_title="Frequency (MHz)",
        yaxis_title="Baseline",
        height=max(400, n_bl * 25),
        template="plotly_white",
    )
    return fig


# --- Sidebar Configuration ---
st.sidebar.title("📡 RRIVis Configuration")

# Antenna Layout
st.sidebar.header("Antenna Array")
antenna_source = st.sidebar.radio(
    "Antenna Layout Source",
    ["Preset Layout", "Custom Layout"],
    index=0,
)

if antenna_source == "Preset Layout":
    layout_name = st.sidebar.selectbox(
        "Select Layout",
        list(ANTENNA_LAYOUT_FILES.keys()),
    )
    antenna_info = ANTENNA_LAYOUT_FILES[layout_name]
    antenna_file_path = ANTENNA_LAYOUTS_DIR / antenna_info["file"]
    antenna_format = antenna_info["format"]
    custom_layout_content = None
else:
    layout_type = st.sidebar.selectbox(
        "Array Geometry",
        ["Linear (E-W)", "Linear (N-S)", "Y-shaped", "Hex Grid", "Random"],
    )
    n_antennas = st.sidebar.slider("Number of Antennas", 3, 30, 10)
    spacing = st.sidebar.slider("Antenna Spacing (m)", 5.0, 50.0, 14.6, step=0.5)
    diameter = st.sidebar.slider("Dish Diameter (m)", 1.0, 25.0, 14.0, step=0.5)
    custom_layout_content = create_custom_antenna_layout(
        n_antennas, layout_type, spacing, diameter
    )
    antenna_format = "rrivis"
    antenna_file_path = None

# Observatory Location
st.sidebar.header("Observatory Location")
location_preset = st.sidebar.selectbox(
    "Observatory",
    list(PRESET_LOCATIONS.keys()),
)
loc = PRESET_LOCATIONS[location_preset]
if location_preset == "Custom":
    lat = st.sidebar.number_input("Latitude (deg)", -90.0, 90.0, 0.0, step=0.01)
    lon = st.sidebar.number_input("Longitude (deg)", -180.0, 180.0, 0.0, step=0.01)
    height = st.sidebar.number_input("Height (m)", 0.0, 5000.0, 0.0, step=1.0)
else:
    lat = loc["lat"]
    lon = loc["lon"]
    height = loc["height"]

# Observation Frequency
st.sidebar.header("Observation Frequency")
freq_start = st.sidebar.number_input(
    "Start Frequency (MHz)", 10.0, 10000.0, 100.0, step=10.0
)
freq_bandwidth = st.sidebar.number_input("Bandwidth (MHz)", 1.0, 1000.0, 50.0, step=5.0)
freq_interval = st.sidebar.number_input(
    "Channel Width (MHz)", 0.1, 100.0, 5.0, step=0.5
)

# Observation Time
st.sidebar.header("Observation Time")
start_time = st.sidebar.text_input("Start Time (UTC)", "2025-01-15T00:00:00")
duration_seconds = st.sidebar.number_input("Duration (seconds)", 1, 86400, 600, step=60)
time_step = st.sidebar.number_input("Time Step (seconds)", 1, 3600, 60, step=10)

# Sky Model
st.sidebar.header("Sky Model")
num_sources = st.sidebar.slider("Number of Test Sources", 1, 200, 10)
flux_min = st.sidebar.number_input("Min Flux (Jy)", 0.01, 100.0, 2.0, step=0.5)
flux_max = st.sidebar.number_input("Max Flux (Jy)", 0.1, 1000.0, 8.0, step=0.5)
spectral_index = st.sidebar.slider("Spectral Index", -3.0, 1.0, -0.8, step=0.1)

# --- Main Content ---
st.title("📡 RRIVis - Radio Interferometer Visibility Simulator")
st.markdown(
    "Simulate radio interferometer visibilities using the **RIME** "
    "(Radio Interferometer Measurement Equation) with full polarization support."
)

# Show current configuration summary
with st.expander("Configuration Summary", expanded=False):
    col1, col2, col3 = st.columns(3)
    with col1:
        st.markdown("**Antenna Array**")
        if antenna_source == "Preset Layout":
            st.write(f"Layout: {layout_name}")
        else:
            st.write(f"Custom: {layout_type}, {n_antennas} antennas")
    with col2:
        st.markdown("**Observation**")
        st.write(f"Freq: {freq_start}–{freq_start + freq_bandwidth} MHz")
        n_channels = max(1, int(freq_bandwidth / freq_interval)) + 1
        st.write(f"Channels: {n_channels}")
        st.write(f"Duration: {duration_seconds}s, step: {time_step}s")
    with col3:
        st.markdown("**Sky Model**")
        st.write(f"Test sources: {num_sources}")
        st.write(f"Flux: {flux_min}–{flux_max} Jy")
        st.write(f"Spectral index: {spectral_index}")

# Run Simulation Button
run_clicked = st.button("🚀 Run Simulation", type="primary", use_container_width=True)

if run_clicked:
    with st.spinner("Running visibility simulation..."):
        try:
            from rrivis import Simulator

            # Write custom layout to temp file if needed
            if custom_layout_content is not None:
                tmp = tempfile.NamedTemporaryFile(
                    mode="w", suffix=".txt", delete=False, prefix="rrivis_layout_"
                )
                tmp.write(custom_layout_content)
                tmp.flush()
                layout_path = tmp.name
            else:
                layout_path = str(antenna_file_path)

            # Build config dict
            config = {
                "antenna_layout": {
                    "antenna_positions_file": layout_path,
                    "antenna_file_format": antenna_format,
                    "all_antenna_diameter": 14.0,
                },
                "location": {
                    "lat": lat,
                    "lon": lon,
                    "height": height,
                },
                "obs_frequency": {
                    "starting_frequency": freq_start,
                    "frequency_bandwidth": freq_bandwidth,
                    "frequency_interval": freq_interval,
                    "frequency_unit": "MHz",
                },
                "obs_time": {
                    "start_time": start_time,
                    "duration_seconds": duration_seconds,
                    "time_step_seconds": time_step,
                },
                "sky_model": {
                    "flux_unit": "Jy",
                    "test_sources": {
                        "use_test_sources": True,
                        "num_sources": num_sources,
                        "flux_min": flux_min,
                        "flux_max": flux_max,
                        "dec_deg": lat,
                        "spectral_index": spectral_index,
                    },
                },
                "output": {
                    "save_simulation_data": False,
                    "plot_results_in_bokeh": False,
                },
            }

            t0 = time.perf_counter()
            sim = Simulator(config=config, backend="numpy", precision="standard")
            sim.setup()
            results = sim.run(progress=False)
            elapsed = time.perf_counter() - t0

            st.session_state["results"] = results
            st.session_state["sim"] = sim
            st.session_state["elapsed"] = elapsed

        except Exception as e:
            st.error(f"Simulation failed: {e}")
            import traceback

            st.code(traceback.format_exc())

# Display results
if "results" in st.session_state:
    results = st.session_state["results"]
    sim = st.session_state["sim"]
    elapsed = st.session_state["elapsed"]

    # Summary metrics
    st.success(f"Simulation completed in {elapsed:.2f}s")

    col1, col2, col3, col4 = st.columns(4)
    meta = results["metadata"]
    col1.metric("Antennas", meta["n_antennas"])
    col2.metric("Baselines", meta["n_baselines"])
    col3.metric("Sources", meta["n_sky_elements"])
    col4.metric("Freq Channels", meta["n_frequencies"])

    # Tabs for different visualizations
    tab1, tab2, tab3, tab4, tab5 = st.tabs(
        [
            "Antenna Layout",
            "UV Coverage",
            "Visibility Amplitude",
            "Visibility Phase",
            "Amplitude Heatmap",
        ]
    )

    with tab1:
        fig = plot_antenna_layout(results["antennas"])
        st.plotly_chart(fig, use_container_width=True)

    with tab2:
        fig = plot_uv_coverage(results["baselines"], results["wavelengths"])
        st.plotly_chart(fig, use_container_width=True)

    with tab3:
        fig = plot_visibility_spectrum(results)
        st.plotly_chart(fig, use_container_width=True)

    with tab4:
        fig = plot_visibility_phase(results)
        st.plotly_chart(fig, use_container_width=True)

    with tab5:
        fig = plot_visibility_matrix(results)
        st.plotly_chart(fig, use_container_width=True)

    # Raw data inspection
    with st.expander("Raw Visibility Data"):
        bl_keys = list(results["visibilities"].keys())
        selected_bl = st.selectbox("Select Baseline", bl_keys)
        if selected_bl:
            bl_vis = results["visibilities"][selected_bl]
            vis_I = bl_vis.get("I", bl_vis.get("XX"))
            if vis_I is not None:
                st.write(f"**Shape:** {vis_I.shape} (time steps x frequency channels)")
                st.write(
                    f"**Amplitude range:** {np.abs(vis_I).min():.4f} – {np.abs(vis_I).max():.4f} Jy"
                )
                st.write(
                    f"**Phase range:** {np.degrees(np.angle(vis_I)).min():.1f} – {np.degrees(np.angle(vis_I)).max():.1f} deg"
                )

    # Timing info
    with st.expander("Timing Details"):
        timing = results["timing"]
        st.write(f"**Total time:** {timing['total']:.3f}s")
        st.write(f"**Setup time:** {timing['setup']:.3f}s")
        st.write(f"**Computation time:** {timing['total'] - timing['setup']:.3f}s")
        st.write(f"**Backend:** {meta['backend']}")
        st.write(f"**Simulator:** {meta['simulator']}")

else:
    st.info(
        "Configure your simulation parameters in the sidebar, then click **Run Simulation**."
    )

    # Show some info about the project
    st.markdown("---")
    st.markdown("### About RRIVis")
    st.markdown(
        """
        RRIVis implements the **Radio Interferometer Measurement Equation (RIME)**:

        $$V_{pq}(\\nu, t) = \\sum_s J_p(s, \\nu, t) \\cdot C_s(\\nu) \\cdot J_q^H(s, \\nu, t)$$

        where:
        - $V_{pq}$ is the visibility for baseline $p$-$q$
        - $J_p$ is the Jones matrix chain for antenna $p$
        - $C_s$ is the coherency matrix for source $s$
        - $J_q^H$ is the Hermitian conjugate of the Jones matrix for antenna $q$

        **Features:**
        - Full Stokes polarization (I, Q, U, V)
        - GPU acceleration via JAX
        - 20+ sky model catalogs (GLEAM, NVSS, TGSS, etc.)
        - Multiple antenna layout formats
        - HDF5 and Measurement Set output

        [GitHub Repository](https://github.com/kartikmandar/RRIvis) |
        [Documentation](https://rrivis.readthedocs.io)
        """
    )
