"""Public immutable beam definitions and assignment resolution."""

from importlib import import_module
from typing import TYPE_CHECKING

from radiosim.core.beam.errors import (
    BeamAngularDomainError,
    BeamAssignmentError,
    BeamDependencyError,
    BeamDisplayNormalizationError,
    BeamError,
    BeamEvaluationError,
    BeamFileChangedError,
    BeamFileReadError,
    BeamFrequencyDomainError,
    BeamLoadError,
    BeamNormalizationError,
    BeamSamplingDerivationError,
    DuplicateBeamAssignmentError,
    IncompleteBeamAssignmentError,
    InconsistentBeamAssignmentError,
    NonFiniteBeamResponseError,
    UnknownBeamAntennaError,
    UnsupportedBeamBasisError,
    UnsupportedBeamCoordinateError,
    UnsupportedBeamFeedError,
    UnsupportedBeamMetadataError,
    UnsupportedBeamPrecisionError,
    UnsupportedBeamTypeError,
)
from radiosim.core.beam.models import (
    BeamAssignmentProvenance,
    BeamFileProvenance,
    LoadedBeamHandlerState,
    LoadedBeamState,
    ResolvedAnalyticalIlluminationBeamModel,
    ResolvedAnalyticBeamChoice,
    ResolvedAnalyticBeamDefinition,
    ResolvedAnalyticBeamModel,
    ResolvedAnalyticBeamsInput,
    ResolvedAntennaPointingOffset,
    ResolvedAntennaSurfaceError,
    ResolvedBeamAssignment,
    ResolvedBeamPointing,
    ResolvedBeamsInput,
    ResolvedBeamState,
    ResolvedBeamSurfaceError,
    ResolvedCassegrainReflector,
    ResolvedCircularApertureBeamModel,
    ResolvedCorrugatedHornIllumination,
    ResolvedCosineTaper,
    ResolvedDerivedGaussianTaper,
    ResolvedDerivedParabolicSquaredTaper,
    ResolvedDerivedParabolicTaper,
    ResolvedDerivedTaper,
    ResolvedDipoleGroundPlaneIllumination,
    ResolvedDirectTaper,
    ResolvedEllipticalApertureBeamModel,
    ResolvedFITSBeamAssignmentInput,
    ResolvedFITSBeamDefinition,
    ResolvedGaussianTaper,
    ResolvedIllumination,
    ResolvedMixedBeamAssignmentInput,
    ResolvedMixedBeamsInput,
    ResolvedNumericalIlluminationBeamModel,
    ResolvedOpenWaveguideIllumination,
    ResolvedParabolicSquaredTaper,
    ResolvedParabolicTaper,
    ResolvedPerAntennaFITSBeamsInput,
    ResolvedPointingOffset,
    ResolvedPrimeFocusReflector,
    ResolvedRectangularApertureBeamModel,
    ResolvedReflector,
    ResolvedSharedFITSBeamsInput,
    ResolvedSurfaceError,
    ResolvedUniformTaper,
)
from radiosim.core.beam.resolution import resolve_beam_assignments

if TYPE_CHECKING:
    from radiosim.core.beam.runtime import BeamSystem, load_beam_system

__all__ = [
    "BeamError",
    "BeamAssignmentError",
    "UnknownBeamAntennaError",
    "DuplicateBeamAssignmentError",
    "IncompleteBeamAssignmentError",
    "InconsistentBeamAssignmentError",
    "BeamLoadError",
    "BeamDependencyError",
    "BeamFileReadError",
    "BeamFileChangedError",
    "UnsupportedBeamMetadataError",
    "UnsupportedBeamTypeError",
    "UnsupportedBeamFeedError",
    "UnsupportedBeamBasisError",
    "UnsupportedBeamCoordinateError",
    "BeamNormalizationError",
    "UnsupportedBeamPrecisionError",
    "BeamSamplingDerivationError",
    "BeamEvaluationError",
    "BeamFrequencyDomainError",
    "BeamAngularDomainError",
    "NonFiniteBeamResponseError",
    "BeamDisplayNormalizationError",
    "BeamAssignmentProvenance",
    "BeamFileProvenance",
    "LoadedBeamHandlerState",
    "LoadedBeamState",
    "BeamSystem",
    "load_beam_system",
    "ResolvedAnalyticBeamChoice",
    "ResolvedAntennaPointingOffset",
    "ResolvedAntennaSurfaceError",
    "ResolvedBeamPointing",
    "ResolvedBeamSurfaceError",
    "ResolvedPointingOffset",
    "ResolvedSurfaceError",
    "ResolvedAnalyticBeamDefinition",
    "ResolvedAnalyticBeamModel",
    "ResolvedAnalyticBeamsInput",
    "ResolvedAnalyticalIlluminationBeamModel",
    "ResolvedBeamsInput",
    "ResolvedCassegrainReflector",
    "ResolvedCircularApertureBeamModel",
    "ResolvedCorrugatedHornIllumination",
    "ResolvedCosineTaper",
    "ResolvedDerivedGaussianTaper",
    "ResolvedDerivedParabolicSquaredTaper",
    "ResolvedDerivedParabolicTaper",
    "ResolvedDerivedTaper",
    "ResolvedDipoleGroundPlaneIllumination",
    "ResolvedDirectTaper",
    "ResolvedEllipticalApertureBeamModel",
    "ResolvedFITSBeamAssignmentInput",
    "ResolvedFITSBeamDefinition",
    "ResolvedGaussianTaper",
    "ResolvedIllumination",
    "ResolvedMixedBeamAssignmentInput",
    "ResolvedMixedBeamsInput",
    "ResolvedNumericalIlluminationBeamModel",
    "ResolvedOpenWaveguideIllumination",
    "ResolvedParabolicSquaredTaper",
    "ResolvedParabolicTaper",
    "ResolvedPerAntennaFITSBeamsInput",
    "ResolvedPrimeFocusReflector",
    "ResolvedRectangularApertureBeamModel",
    "ResolvedBeamAssignment",
    "ResolvedBeamState",
    "ResolvedReflector",
    "ResolvedSharedFITSBeamsInput",
    "ResolvedUniformTaper",
    "resolve_beam_assignments",
]


def __getattr__(name: str) -> object:
    if name in {"BeamSystem", "load_beam_system"}:
        value = getattr(import_module("radiosim.core.beam.runtime"), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    """Include lazy runtime exports in interactive discovery."""
    return sorted(set(globals()) | {"BeamSystem", "load_beam_system"})
