"""Public ``load_<catalog>`` wrappers for VizieR point-source catalogs.

Each wrapper is a thin call to ``_load_from_vizier_catalog`` with a
fixed ``catalog_key``. The 7 simple catalogs (vlssr, tgss, wenss,
sumss, nvss, 3c, vlass) are generated by the
``_make_simple_vizier_loader`` factory; gleam, mals, and lotss are
written explicitly because they need extra columns or column-mapping
logic.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from ...operations.region import SkyRegion
from ...registry.catalogs import VIZIER_POINT_CATALOGS
from ...registry.facade import loader_registry
from .core import (
    _load_from_vizier_catalog,
)

if TYPE_CHECKING:
    from radiosim.core.precision import PrecisionConfig

logger = logging.getLogger(__name__)


@loader_registry.register_loader(
    "gleam",
    config_section="gleam",
    use_flag="use_gleam",
    network_service="vizier",
    aliases={
        "gleam_egc": {"catalog": "gleam_egc"},
        "gleam_x_dr1": {"catalog": "gleam_x_dr1"},
        "gleam_x_dr2": {"catalog": "gleam_x_dr2"},
        "gleam_gal": {"catalog": "gleam_gal"},
    },
    config_fields={
        "flux_limit": "flux_limit",
        "catalog": "catalog",
        "max_rows": "max_rows",
        "allow_full_catalog": "allow_full_catalog",
    },
)
def load_gleam(
    flux_limit: float = 1.0,
    catalog: str = "gleam_egc",
    brightness_conversion: str = "planck",
    *,
    precision: PrecisionConfig,
    region: SkyRegion | None = None,
    max_rows: int | None = None,
    allow_full_catalog: bool = False,
) -> SkyModel:  # noqa: F821
    """
    Load GLEAM catalog from VizieR.

    Parameters
    ----------
    flux_limit : float, default=1.0
        Minimum flux density in Jy.
    catalog : str, default="gleam_egc"
        Catalog key in ``VIZIER_POINT_CATALOGS``. Available GLEAM
        catalogs: ``"gleam_egc"``, ``"gleam_x_dr1"``, ``"gleam_x_dr2"``,
        ``"gleam_gal"``.
    precision : PrecisionConfig
        Precision configuration for array dtypes.

    Returns
    -------
    SkyModel
        Sky model with GLEAM sources.
    """
    _gleam_keys = sorted(k for k in VIZIER_POINT_CATALOGS if k.startswith("gleam"))
    if catalog not in VIZIER_POINT_CATALOGS:
        raise ValueError(f"Unknown GLEAM catalog '{catalog}'. Available: {_gleam_keys}")
    return _load_from_vizier_catalog(
        catalog,
        flux_limit,
        brightness_conversion,
        precision,
        region=region,
        max_rows=max_rows,
        allow_full_catalog=allow_full_catalog,
    )


@loader_registry.register_loader(
    "mals",
    config_section="mals",
    use_flag="use_mals",
    network_service="vizier",
    aliases={
        "mals_dr1": {"release": "dr1"},
        "mals_dr2": {"release": "dr2"},
    },
    config_fields={
        "flux_limit": "flux_limit",
        "release": "release",
        "max_rows": "max_rows",
        "allow_full_catalog": "allow_full_catalog",
    },
)
def load_mals(
    flux_limit: float = 1.0,
    release: str = "dr2",
    brightness_conversion: str = "planck",
    *,
    precision: PrecisionConfig,
    region: SkyRegion | None = None,
    max_rows: int | None = None,
    allow_full_catalog: bool = False,
) -> SkyModel:  # noqa: F821
    """
    Load MALS catalog from VizieR.

    Parameters
    ----------
    flux_limit : float, default=1.0
        Minimum flux density in Jy. The catalog stores flux in mJy;
        unit conversion is handled internally by the generic loader.
    release : str, default="dr2"
        Data release: "dr1" or "dr2".
    precision : PrecisionConfig
        Precision configuration for array dtypes.

    Returns
    -------
    SkyModel
        Sky model with MALS sources.
    """
    key = f"mals_{release.lower()}"
    if key not in VIZIER_POINT_CATALOGS:
        raise ValueError(f"Unknown MALS release '{release}'. Available: 'dr1', 'dr2'.")
    return _load_from_vizier_catalog(
        key,
        flux_limit,
        brightness_conversion,
        precision,
        region=region,
        max_rows=max_rows,
        allow_full_catalog=allow_full_catalog,
    )


# =========================================================================
# Data-driven registration of simple VizieR loaders
# =========================================================================

# Catalog keys with only flux_limit as their config-driven parameter.
# Complex loaders (gleam, mals, lotss, racs) are kept as explicit functions.
_SIMPLE_VIZIER_CATALOGS = {
    "vlssr": "vlssr",
    "tgss": "tgss",
    "wenss": "wenss",
    "sumss": "sumss",
    "nvss": "nvss",
    "3c": "three_c",  # config_section differs from loader name
    "vlass": "vlass",
}


def _make_simple_vizier_loader(catalog_key: str):
    """Create a simple VizieR loader function for *catalog_key*."""
    info = VIZIER_POINT_CATALOGS[catalog_key]

    def loader(
        flux_limit: float = info.default_flux_limit,
        brightness_conversion: str = "planck",
        *,
        precision: PrecisionConfig,
        region: SkyRegion | None = None,
        max_rows: int | None = None,
        allow_full_catalog: bool = False,
    ):
        return _load_from_vizier_catalog(
            catalog_key,
            flux_limit,
            brightness_conversion,
            precision,
            region=region,
            max_rows=max_rows,
            allow_full_catalog=allow_full_catalog,
        )

    loader.__name__ = f"load_{catalog_key}"
    loader.__qualname__ = f"load_{catalog_key}"
    loader.__doc__ = (
        f"Load the {catalog_key.upper()} catalog from VizieR.\n\n"
        f"{info.description}\n\n"
        f"Parameters\n----------\n"
        f"flux_limit : float, default={info.default_flux_limit}\n"
        f"    Minimum flux density in Jy.\n"
        f"brightness_conversion : str, default='planck'\n"
        f"    Conversion method: 'planck' or 'rayleigh-jeans'.\n"
        f"precision : PrecisionConfig\n"
        f"    Precision configuration for array dtypes.\n"
        f"region : SkyRegion, optional\n"
        f"    Spatial filter.\n\n"
        f"Returns\n-------\nSkyModel\n"
    )
    return loader


for _key, _config_section in _SIMPLE_VIZIER_CATALOGS.items():
    _fn = _make_simple_vizier_loader(_key)
    loader_registry.register_loader(
        _key,
        config_section=_config_section,
        use_flag=f"use_{_key}",
        network_service="vizier",
        config_fields={
            "flux_limit": "flux_limit",
            "max_rows": "max_rows",
            "allow_full_catalog": "allow_full_catalog",
        },
    )(_fn)

# Expose as module-level names for direct import
load_vlssr = loader_registry.loader("vlssr")
load_tgss = loader_registry.loader("tgss")
load_wenss = loader_registry.loader("wenss")
load_sumss = loader_registry.loader("sumss")
load_nvss = loader_registry.loader("nvss")
load_3c = loader_registry.loader("3c")
load_vlass = loader_registry.loader("vlass")


@loader_registry.register_loader(
    "lotss",
    config_section="lotss",
    use_flag="use_lotss",
    network_service="vizier",
    aliases={
        "lotss_dr1": {"release": "dr1"},
        "lotss_dr2": {"release": "dr2"},
    },
    config_fields={
        "flux_limit": "flux_limit",
        "release": "release",
        "max_rows": "max_rows",
        "allow_full_catalog": "allow_full_catalog",
    },
)
def load_lotss(
    flux_limit: float = 0.001,
    release: str = "dr2",
    brightness_conversion: str = "planck",
    *,
    precision: PrecisionConfig,
    region: SkyRegion | None = None,
    max_rows: int | None = None,
    allow_full_catalog: bool = False,
) -> SkyModel:  # noqa: F821
    """
    Load the LoTSS catalog from VizieR (144 MHz, DR1: ~325k, DR2: ~4.4M sources).

    LoTSS (Shimwell et al.) is the LOFAR Two-metre Sky Survey at 144 MHz.
    DR1: J/A+A/622/A1, DR2: J/A+A/659/A1 on VizieR.

    Parameters
    ----------
    release : str, default="dr2"
        Data release: "dr1" or "dr2".
    flux_limit : float, default=0.001
        Minimum flux density in Jy.
    brightness_conversion : str, default="planck"
        Conversion method: "planck" or "rayleigh-jeans".
    precision : PrecisionConfig
        Precision configuration for array dtypes.

    Returns
    -------
    SkyModel

    Raises
    ------
    ValueError
        If ``release`` is not "dr1" or "dr2".
    """
    key = f"lotss_{release.lower()}"
    if key not in VIZIER_POINT_CATALOGS:
        raise ValueError(f"Unknown LoTSS release '{release}'. Available: 'dr1', 'dr2'.")
    return _load_from_vizier_catalog(
        key,
        flux_limit,
        brightness_conversion,
        precision,
        region=region,
        max_rows=max_rows,
        allow_full_catalog=allow_full_catalog,
    )
